#ifndef COLORS_HPP
#define COLORS_HPP

#define NCURSES_COLOR 1000/255
#define MYCOLOR_AQUA_PAIR 8
#define MYCOLOR_BLACK_BG_PAIR 9
#define MYCOLOR_USERNAME_PAIR 11
#define MYCOLOR_WHITE_PAIR 12
#define MYCOLOR_RED_BG_PAIR 13
#define MYCOLOR_CYAN_PAIR 14
#define MYCOLOR_CYAN_BLACK_PAIR 15

#define MYCOLOR_GREEN_PAIR 17
#define MYCOLOR_RED_PAIR 18
#define MYCOLOR_YELLOW_PAIR 19

#define MYCOLOR_GREEN_BLACK_PAIR 20
#define MYCOLOR_RED_BLACK_PAIR 21
#define MYCOLOR_YELLOW_BLACK_PAIR 22

#endif // COLORS_HPP
